export const HEGIC_OPTIONS_FACTORY_ADDRESS = '0x06194062288575f35c0af45d5e7013b65e082f23'

export const ETHERSCAN_URL = 'https://etherscan.io/'
export const ADDRESS = 'address/'
export const TRANSACTION = 'tx/'


export const ERROR = 'ERROR'

export const CONFIGURE = 'CONFIGURE'
export const CONFIGURE_RETURNED = 'CONFIGURE_RETURNED'

export const CONNECTION_CONNECTED = 'CONNECTION_CONNECTED'
export const CONNECTION_DISCONNECTED = 'CONNECTION_DISCONNECTED'

export const GET_BALANCES = 'GET_BALANCES'
export const BALANCES_RETURNED = 'BALANCES_RETURNED'

export const GET_OPTIONS = 'GET_OPTIONS'
export const OPTIONS_RETURNED = 'OPTIONS_RETURNED'

export const GET_OPTIONS_FEES = 'GET_OPTIONS_FEES'
export const OPTIONS_FEES_RETURNED = 'OPTIONS_FEES_RETURNED'

export const CREATE_OPTION = 'CREATE_OPTION'
export const CREATE_OPTION_RETURNED = 'CREATE_OPTION_RETURNED'
