export const OPTIONS_RESERVE_ADDRESS = '0x3d07f261783d9ACDa6c0827Dc4e40F6025c18ec3'
export const OPTIONS_CONTRACTS_ADDRESS = '0xec10adfc9185c896e07928add0c10a908c10ca91'
export const KEEPER_ORACLE_ADDRESS = '0x73353801921417f465377c8d898c6f4c0270282c'

export const ETHERSCAN_URL = 'https://etherscan.io/'
export const ADDRESS = 'address/'
export const TRANSACTION = 'tx/'


export const ERROR = 'ERROR'

export const CONFIGURE = 'CONFIGURE'
export const CONFIGURE_RETURNED = 'CONFIGURE_RETURNED'

export const CONNECTION_CONNECTED = 'CONNECTION_CONNECTED'
export const CONNECTION_DISCONNECTED = 'CONNECTION_DISCONNECTED'

export const GET_BALANCES = 'GET_BALANCES'
export const BALANCES_RETURNED = 'BALANCES_RETURNED'

export const GET_OPTIONS = 'GET_OPTIONS'
export const OPTIONS_RETURNED = 'OPTIONS_RETURNED'

export const GET_OPTIONS_FEES = 'GET_OPTIONS_FEES'
export const OPTIONS_FEES_RETURNED = 'OPTIONS_FEES_RETURNED'

export const CREATE_OPTION = 'CREATE_OPTION'
export const CREATE_OPTION_RETURNED = 'CREATE_OPTION_RETURNED'
